// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// comte
List comte(arma::mat y, arma::mat x, arma::mat S, double tol, int maxit, Nullable<NumericVector> min_s2, double scale, double cutoff);
RcppExport SEXP _cole_comte(SEXP ySEXP, SEXP xSEXP, SEXP SSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP min_s2SEXP, SEXP scaleSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type min_s2(min_s2SEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(comte(y, x, S, tol, maxit, min_s2, scale, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// predict_comte
arma::mat predict_comte(List comte_obj, arma::mat newx);
RcppExport SEXP _cole_predict_comte(SEXP comte_objSEXP, SEXP newxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type comte_obj(comte_objSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type newx(newxSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_comte(comte_obj, newx));
    return rcpp_result_gen;
END_RCPP
}
// rep_time
arma::vec rep_time(arma::vec s, int times);
RcppExport SEXP _cole_rep_time(SEXP sSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(rep_time(s, times));
    return rcpp_result_gen;
END_RCPP
}
// rep_each
arma::vec rep_each(arma::vec s, int each);
RcppExport SEXP _cole_rep_each(SEXP sSEXP, SEXP eachSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type each(eachSEXP);
    rcpp_result_gen = Rcpp::wrap(rep_each(s, each));
    return rcpp_result_gen;
END_RCPP
}
// npmle_c
arma::vec npmle_c(arma::mat D, int maxit, double tol, bool verbose);
RcppExport SEXP _cole_npmle_c(SEXP DSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(npmle_c(D, maxit, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// msg
arma::mat msg(arma::mat X, int d, bool centered, int maxit, double tol, bool verbose);
RcppExport SEXP _cole_msg(SEXP XSEXP, SEXP dSEXP, SEXP centeredSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type centered(centeredSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(msg(X, d, centered, maxit, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
